;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
GameplayTagList=(Tag="UI.Settings.Audio.Master",DevComment="")
GameplayTagList=(Tag="UI.Settings.Audio.Music",DevComment="")
GameplayTagList=(Tag="UI.Settings.Audio.SFX",DevComment="")
GameplayTagList=(Tag="UI.Settings.Audio.Voice",DevComment="")
GameplayTagList=(Tag="UI.Settings.Controls.GamepadSens",DevComment="")
GameplayTagList=(Tag="UI.Settings.Controls.MouseSens",DevComment="")
GameplayTagList=(Tag="UI.Settings.Graphics",DevComment="")
GameplayTagList=(Tag="UI.Settings.Graphics.Graphics",DevComment="")
GameplayTagList=(Tag="UI.Settings.Graphics.Resolution",DevComment="")
GameplayTagList=(Tag="UI.Settings.Graphics.Window",DevComment="")

